"""add fields to authors

Revision ID: 279fd37fbaab
Revises: 3862ad261808
Create Date: 2026-03-06 10:03:22.738629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279fd37fbaab'
down_revision: Union[str, Sequence[str], None] = '3862ad261808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('authors', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'country')
    op.drop_column('authors', 'birth_date')
    # ### end Alembic commands ###
